name: Deploy
on:
  push:
    branches:
      - develop
      - release/*
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: ${{ (github.ref == 'refs/heads/develop' && 'develop') || ((startsWith('refs/heads/release', github.ref) && 'staging') || 'production') }}

    steps:
      - uses: actions/checkout@v3

      - name: print ref
        env:
          GITHUB_REF: ${{ github.ref }}
        run: echo $GITHUB_REF

      - name: print event name
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: echo $GITHUB_EVENT_NAME

      - name: print env
        env:
          ENV_NAME: ${{ (github.ref == 'refs/heads/develop' && 'develop') || ((startsWith('refs/heads/release', github.ref) && 'staging') || 'production') }}
        run: echo $ENV_NAME

      - name: print secret
        run: echo ${{ secrets.ACCESS_KEY }}
